import * as vscode from 'vscode';
import * as path from 'path';
import { LanguageClient, LanguageClientOptions, ServerOptions, TransportKind } from 'vscode-languageclient/node';
import { exploitFunctions } from './exploitSignatures';

export class LuauLSPProvider {
    private client?: LanguageClient;
    private definitionsFile?: vscode.Uri;

    constructor(
        private readonly context: vscode.ExtensionContext,
        private readonly outputChannel: vscode.OutputChannel
    ) {}

    public async activate(): Promise<void> {
        const config = vscode.workspace.getConfiguration('exploitor');
        const enabled = config.get<boolean>('lsp.enabled', true);

        if (!enabled) {
            this.outputChannel.appendLine('[LSP] Disabled in settings');
            return;
        }

        try {
            // Check if luau-lsp is available
            const hasLuauLsp = await this.checkLuauLsp();
            if (!hasLuauLsp) {
                this.outputChannel.appendLine('[LSP] luau-lsp not found in PATH');
                this.showInstallPrompt();
                return;
            }

            // Create exploit definitions file
            await this.createExploitDefinitions();

            // Start language server
            await this.startLanguageServer();

            this.outputChannel.appendLine('[LSP] Activated successfully');
        } catch (err) {
            this.outputChannel.appendLine(`[LSP] Activation failed: ${err}`);
        }
    }

    private async checkLuauLsp(): Promise<boolean> {
        try {
            const { exec } = require('child_process');
            const { promisify } = require('util');
            const execAsync = promisify(exec);

            await execAsync('luau-lsp --version');
            return true;
        } catch {
            return false;
        }
    }

    private showInstallPrompt(): void {
        vscode.window.showInformationMessage(
            'luau-lsp is not installed. Install it for better Luau language support.',
            'Install Guide',
            'Disable LSP'
        ).then(selection => {
            if (selection === 'Install Guide') {
                vscode.env.openExternal(vscode.Uri.parse('https://github.com/JohnnyMorganz/luau-lsp#installation'));
            } else if (selection === 'Disable LSP') {
                vscode.workspace.getConfiguration('exploitor').update('lsp.enabled', false, true);
            }
        });
    }

    private async createExploitDefinitions(): Promise<void> {
        const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
        if (!workspaceFolder) {
            this.outputChannel.appendLine('[LSP] No workspace folder found');
            return;
        }

        const luauDir = path.join(workspaceFolder.uri.fsPath, '.luaurc');
        const defsDir = path.join(luauDir, 'definitions');

        // Create definitions content
        let definitions = '-- Exploit API Definitions\n';
        definitions += '-- Generated by ExploUtor\n\n';
        definitions += 'declare class ExploitAPI\n';

        // Group by category
        const categories = new Map<string, typeof exploitFunctions>();
        for (const func of exploitFunctions) {
            if (!categories.has(func.category)) {
                categories.set(func.category, []);
            }
            categories.get(func.category)!.push(func);
        }

        // Generate declarations
        for (const [category, funcs] of categories) {
            definitions += `\n  -- ${category} Functions\n`;
            for (const func of funcs) {
                definitions += `  ${func.signature}\n`;
            }
        }

        definitions += 'end\n\n';

        // Add global declarations
        definitions += '-- Global exploit functions\n';
        for (const func of exploitFunctions) {
            definitions += `declare ${func.signature}\n`;
        }

        // Write to .luaurc/definitions/exploit.d.luau
        try {
            const fs = require('fs/promises');
            await fs.mkdir(defsDir, { recursive: true });

            const defsPath = path.join(defsDir, 'exploit.d.luau');
            await fs.writeFile(defsPath, definitions, 'utf-8');

            this.definitionsFile = vscode.Uri.file(defsPath);
            this.outputChannel.appendLine(`[LSP] Created definitions at ${defsPath}`);

            // Create .luaurc config if it doesn't exist
            await this.createLuaurcConfig(luauDir);
        } catch (err) {
            this.outputChannel.appendLine(`[LSP] Failed to create definitions: ${err}`);
        }
    }

    private async createLuaurcConfig(luauDir: string): Promise<void> {
        const configPath = path.join(luauDir, '.luaurc');
        const fs = require('fs/promises');

        try {
            // Check if config already exists
            await fs.access(configPath);
            this.outputChannel.appendLine('[LSP] .luaurc already exists');
        } catch {
            // Create new config
            const config = {
                languageMode: 'strict',
                aliases: {
                    exploit: 'definitions/exploit.d.luau'
                }
            };

            await fs.writeFile(configPath, JSON.stringify(config, null, 2), 'utf-8');
            this.outputChannel.appendLine(`[LSP] Created .luaurc config at ${configPath}`);
        }
    }

    private async startLanguageServer(): Promise<void> {
        const serverOptions: ServerOptions = {
            command: 'luau-lsp',
            args: ['lsp']
        };

        const clientOptions: LanguageClientOptions = {
            documentSelector: [
                { scheme: 'file', language: 'luau' },
                { scheme: 'file', language: 'lua', pattern: '**/*.luau' }
            ],
            outputChannel: this.outputChannel,
            synchronize: {
                fileEvents: vscode.workspace.createFileSystemWatcher('**/.luaurc')
            }
        };

        this.client = new LanguageClient(
            'luauLsp',
            'Luau Language Server',
            serverOptions,
            clientOptions
        );

        await this.client.start();
        this.outputChannel.appendLine('[LSP] Language server started');
    }

    public async deactivate(): Promise<void> {
        if (this.client) {
            await this.client.stop();
            this.outputChannel.appendLine('[LSP] Language server stopped');
        }
    }
}
